/**
 * 
 * @param {Object} options 
 * @returns {String}
 */
export const getTemplate = (options) => ` // AUTO-GENERATED BY FOUNDRY
import {JSONDatasource } from '../../__providers/datasources/json.js;

export const Database = (() => {
    return {
        async init() {
            return new JSONDatasource();     
        }
    }
})()

`;